version: '3.7'

services:
 
  redis-master:
    image: redis:latest
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"
    network_mode: host
    container_name: redis-master
  
#  redis-slave:
#    image: redis:latest
#    command: redis-server --slaveof <MASTER HOST IP> 6379
##   links: #    - redis-master
#    volumes:
#      - "./.data:/data"
#   network_mode: host
#    container_name: redis-slave

   
  # Instance 1
  redis-sentinel:
    build: 
      context: ./redis-sentinel
    depends_on:
      - redis-master 
    network_mode: host
    container_name: sentinel-1
